import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Providers from '@/provider/Provider';
import Navbar from '@/components/navbar/Navbar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                <Providers>
                    <div className='bg-slate-900 py-6'>
                        <Header />
                        <Navbar />
                    </div>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
