import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body>
                        <Header />
                        <Navbar />
                {children}
                {/* <Footer /> */}
            </body>
        </html>
    );
}
